export interface TradeModel {
  block_number: number,
  tx_index: number,
  address: string,
  tx_hash: string,
  sender: string,
  in_token_address: string,
  in_token_symbol: string,
  in_token_decimals: number,
  out_token_address: string,
  out_token_symbol: string,
  out_token_decimals: number,
  in_amount: string,
  in_amount_value: string,
  out_amount: string,
  out_amount_value: string,
  referrer: string,
  referrer_fee: string,
  fee: string,
  usd_valuation: number,
  create_at: string,
  update_at: string,
  tx_fee: string,
  tx_fee_valuation: string,
}

